url: "https://iota-school.github.io/accessibility_hackathon" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
root: /
title: "Space Telescope Science Institute Accessible Notebooks Hackathon" # the name of your site, e.g. ACME Corp.


collections:
collections:
  projects:
    output: true
    order:
     - stsci.md
